<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "reviews".
 *
 * @property int $id
 * @property int $program_id
 * @property string $title
 * @property string $pluses
 * @property string $minuses
 * @property string $common
 * @property int $user_id
 * @property int $using_time
 * @property int $rating_convenience
 * @property int $rating_functions
 * @property int $rating_support
 * @property int $created_at
 * @property int $status
 */
class Reviews extends \yii\db\ActiveRecord
{

    public static function mapStatuses()
    {
        return [
            0 => 'Не проможерирован',
            1 => 'Одобрен',
            2 => "Отклонен"
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'reviews';
    }

    public function apply()
    {
        $this->status = 1;
        $this->update(false);

    }

    public function deny()
    {
        $this->status = 2;
        $this->update(false);

    }

    public function beforeValidate()
    {
        $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($program = Programs::findOne($this->program_id)) $program->updateRatings();
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['program_id', 'user_id', 'using_time', 'rating_convenience', 'rating_functions', 'rating_support', 'created_at', 'status'], 'integer'],
            [['title', 'created_at', 'user_id'], 'required'],
            [['pluses', 'minuses', 'common'], 'string'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'program_id' => 'Program ID',
            'title' => 'Title',
            'pluses' => 'Pluses',
            'minuses' => 'Minuses',
            'common' => 'Common',
            'user_id' => 'User ID',
            'using_time' => 'Using Time',
            'rating_convenience' => 'Rating Convenience',
            'rating_functions' => 'Rating Functions',
            'rating_support' => 'Rating Support',
            'created_at' => 'Created At',
            'status' => 'Status',
        ];
    }

    public function formName()
    {
        return '';
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
}
